language: node_js
os:
  - osx
  - linux
node_js:
  - 10
# install:
#   - npm install
# script:
#   - ./node_modules/.bin/tsc
#   - node out/script_tpl.js
#   - npm run test_base


install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

script:
  - |
    echo ">>> Compile vscode-test"
    yarn && yarn compile
    echo ">>> Compiled vscode-test"
    cd sample
    echo ">>> Run sample integration test"
    yarn && yarn compile && yarn lint && yarn test
cache: yarn