on:
  push:
    tags:
      - v*

# copy from 
# https://www.eliostruyf.com/publishing-vscode-extensions-github-actions/
name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Install vsce
        run: npm i -g vsce

      - name: Install the dependencies
        run: yarn && yarn compile

      - name: Publish
        run: vsce publish -p ${{ secrets.VSCE_TOKEN }}
